#=========================================
# Execution Configuration
#=========================================

# Execution Mode
# Supported Values : LOCAL | GRID
execution.mode=GRID

# Selenium Grid URL
grid.url=http://localhost:4444
#=========================================
# Browser Configuration
#=========================================

# Supported Values : CHROME | EDGE | FIREFOX
browser=CHROME

# Supported Values : true | false
headless=false

#=========================================
# Environment Configuration
#=========================================

# Supported Values : QA | UAT | PROD
environment=QA

#=========================================
# Timeout Configuration (Seconds)
#=========================================

implicit.wait=10
explicit.wait=40
page.load.timeout=90