#=========================================
# Test Case Execution Configuration
#=========================================

test.execution.mode=SINGLE
testcase.ids=TC001

#=========================================
# Driver Execution Configuration
#=========================================

driver.execution.mode=LOCAL
#driver.execution.mode=GRID

grid.url=http://localhost:4444

#=========================================
# Browser Configuration
#=========================================

browser=CHROME
headless=false

#=========================================
# Environment Configuration
#=========================================

environment=QA

#=========================================
# Timeout Configuration
#=========================================

implicit.wait=10
explicit.wait=40
page.load.timeout=90